#ifndef MODEL_CONVERTER_H_INCLUDE
#define MODEL_CONVERTER_H_INCLUDE

#include "ModelShell.h"

//----------------------------------------------------------------
//  ModelConverter
//----------------------------------------------------------------

class ModelConverter : public ModelShell {
public:
	ModelConverter() ;
	virtual ~ModelConverter() ;
	ModelConverter( const ModelConverter &src ) ;
	ModelConverter &operator=( const ModelConverter &src ) ;

	int Run( int argc, const char **argv ) ;

protected:
	bool Startup( int argc, const char **argv ) ;
	bool Process() ;
	void Finish() ;

	bool Batch( const string &target, const string &infile, bool enabled = true ) ;
	bool Import( const string &target, const string &infile ) ;
	bool Merge( const string &target, const string &source ) ;
	bool Filter( const string &target ) ;
	bool Filter2( const string &target ) ;
	bool Export( const string &target, const string &infile, int suffix ) ;
	bool Export( const string &target, const string &outfile ) ;
} ;

//----------------------------------------------------------------
//  builtin configuration
//----------------------------------------------------------------

static const char *ModelConverter_BuiltinConfig[] = {
	"usage {",
	"    puts \"usage:\"",
	"    puts \"        ModelConverter <input files> [options]\"",
	"    puts \"options:\"",
	"    puts \"        -o <filename>   specify output filename\"",
	"    puts \"        -s <scale>      scale geometry size\"",
	"    puts \"        -t <scale>      scale animation speed\"",
	"    puts \"        -S              output in text format\"",
	"    puts \"        -N              do not optimize\"",
	"    puts \"        -models         merge models into one file\"",
	"    puts \"        -motions        merge motions into one file\"",
	"}",
	"",
	"default {",
	"    load \"module/*\"",
	"    interact_mode = ctrl",
	"    merge_mode = off",
	"    prompt_mode = off",
	"    output_object = on",
	"    output_script = off",
	"    output_filename = \"\"",
	"    object_extension = .mdx",
	"    script_extension = .mds",
	"    image_extension = .png .jpg .bmp .gif",
	"    filter_script = \"Filter\"",
	"    filter_script2 = \"\"",
	"    size_scale = 1.0",
	"    time_scale = 1.0",
	"    frame_loop = default",
	"    frame_rate = default",
	"    frame_repeat = default",
	"    embed_image = on",
	"    rebuild_bbox = off",
	"    rebuild_bsphere = on",
	"    rebuild_triangle = on",
	"    rebuild_keyframe = on",
	"    unify_mesh = on",
	"    unify_arrays = on",
	"    unify_vertex = on",
	"    unify_material = on",
	"    unify_texture = on",
	"    sort_type = on",
	"    clear_block_name = 2",
	"    epsilon_translate = 0.001",
	"    epsilon_rotate = 0.001",
	"    epsilon_scale = 0.001",
	"    epsilon_misc = 0.001",
	"    epsilon_static = -1.0",
	"    output_name = on",
	"    output_anchor = auto",
	"    output_bone = on",
	"    output_part = on",
	"    output_material = on",
	"    output_texture = on",
	"    output_motion = on",
	"    format_position = default",
	"    format_normal = default",
	"    format_color = default",
	"    format_texcoord = default",
	"    format_weight = default",
	"    format_keyframe = default",
	"    format_filename = full",
	"}",
	"",
	"input *.dae {",
	"    load \"plugin/ImportDAE\"",
	"}",
	"",
	"input *.fbx {",
	"    load \"plugin/ImportFBX\"",
	"}",
	"",
	"input *.xsi {",
	"    load \"plugin/ImportXSI\"",
	"}",
	"",
	"input *.x {",
	"    load \"plugin/ImportX\"",
	"}",
	"",
	"input *.mdx {",
	"}",
	"",
	"input *.mds {",
	"}",
	"",
	"option -interact {",
	"    interact_mode = on",
	"}",
	"",
	"option -models {",
	"    merge_mode = model",
	"}",
	"",
	"option -motions {",
	"    merge_mode = motion",
	"}",
	"",
	"option -prompt {",
	"    prompt_mode = on",
	"}",
	"",
	"option -warning {",
	"    prompt_mode = warning",
	"}",
	"",
	"option -error {",
	"    prompt_mode = error",
	"}",
	"",
	"option -o %filename {",
	"    output_filename = %filename",
	"}",
	"",
	"option -s %scale {",
	"    size_scale = %scale",
	"}",
	"",
	"option -t %scale {",
	"    time_scale = %scale",
	"}",
	"",
	"option -r %fps {",
	"    frame_rate = %fps",
	"}",
	"",
	"option -N {",
	"    rebuild_triangle = off",
	"    rebuild_keyframe = off",
	"    unify_mesh = off",
	"    unify_arrays = off",
	"    unify_vertex = off",
	"    unify_material = off",
	"    unify_texture = off",
	"    clear_block_name = off",
	"}",
	"",
	"option -O {",
	"    rebuild_triangle = on",
	"    rebuild_keyframe = on",
	"    unify_mesh = off",
	"    unify_arrays = off",
	"    unify_vertex = off",
	"    unify_material = on",
	"    unify_texture = on",
	"    clear_block_name = 2",
	"}",
	"",
	"option -S {",
	"    output_object = off",
	"    output_script = on",
	"}",
	"",
	"option -V16 {",
	"    format_position = half",
	"    format_normal = byte",
	"    format_color = ubyte",
	"    format_texcoord = half",
	"    format_weight = ubyte",
	"}",
	"",
	"option -V8 {",
	"    format_position = byte",
	"    format_normal = byte",
	"    format_color = ubyte",
	"    format_texcoord = ubyte",
	"    format_weight = ubyte",
	"}",
	"",
	"script Filter %target {",
	"    CompFCurveChannel       %target on",
	"    ScaleSize               %target $size_scale",
	"    ScaleTime               %target $time_scale",
	"    SetFrameLoop            %target $frame_loop",
	"    SetFrameRate            %target $frame_rate",
	"    SetFrameRepeat          %target $frame_repeat",
	"    UnifyTexture            %target $unify_texture",
	"    UnifyMaterial           %target $unify_material",
	"    UnifyVertex             %target $unify_vertex",
	"    UnifyMesh               %target $unify_mesh",
	"    LimitVertexBlend        %target 4 16",
	"    UnifyArrays             %target $unify_arrays",
	"    RebuildBoundingBox      %target $rebuild_bbox",
	"    RebuildBoundingSphere   %target $rebuild_bsphere",
	"    RebuildTriangle         %target $rebuild_triangle",
	"    RebuildKeyFrame         %target $rebuild_keyframe",
	"    ClearBlockName          %target $clear_block_name",
	"    EmbedImage              %target $embed_image",
	"    SortByType              %target $sort_type",
	"}",

       0,
} ;


#endif

